# Generated by Django 4.2.29 on 2026-03-31 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_order_delivery_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AddField(
            model_name='order',
            name='cnpj',
            field=models.CharField(default='', max_length=14, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='order',
            name='nfe',
            field=models.CharField(default='', max_length=20, verbose_name='Número NFE'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data Entrega'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(verbose_name='Data Pedido'),
        ),
    ]
