# Generated by Django 4.2.29 on 2026-03-31 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_alter_order_options_order_cnpj_order_nfe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='', max_length=20, verbose_name='Status'),
        ),
    ]
