# Generated by Django 4.2.29 on 2026-04-06 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cnpj',
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(default='', max_length=20)),
                ('cnpj', models.CharField(default='', max_length=14, verbose_name='CNPJ')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.city')),
            ],
        ),
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('cnpj', models.CharField(default='', max_length=14, verbose_name='CNPJ')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.city')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='carrier',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tracking.carrier'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tracking.customer'),
        ),
    ]
