# Generated by Django 6.0.4 on 2026-05-04 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_remove_order_cnpj_customer_carrier_order_carrier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='collection_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data Coleta'),
        ),
        migrations.AlterField(
            model_name='order',
            name='carrier',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tracking.carrier', verbose_name='Transportadora'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tracking.customer', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('TRANSITO', 'Em Trânsito'), ('ENTREGUE', 'Entregue')], default='PENDENTE', max_length=20, verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['nfe'], name='tracking_or_nfe_df22da_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='tracking_or_status_d6f4dc_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_date'], name='tracking_or_order_d_3433e3_idx'),
        ),
    ]
