# Generated by Django 6.0.5 on 2026-05-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_order_collection_date_alter_order_carrier_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['cnpj'], name='tracking_cu_cnpj_1957a3_idx'),
        ),
    ]
