name: Trigger auto deployment for fastlog

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/fastlog-AutoDeployTrigger-18d2ec09-3d93-4d2f-9679-e8775a2f607b.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.FASTLOG_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}src
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: docker.io
          registryUsername: ${{ secrets.FASTLOG_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FASTLOG_REGISTRY_PASSWORD }}
          containerAppName: fastlog
          resourceGroup: univesp-pi-05
          imageToBuild: oberdannunes/fastlog:${{ github.sha }}
          
            

     

